config/routes.rb
Rails.application.routes.draw do
  
  resources :maps

  get "/hackita" => 'hackita#index'

  get "/test" => 'test#index'
get "/mp3s" => 'test#mp3s'

  resources :joiners

  resources :constituent_types

  resources :joins

  resources :lamps

  resources :constituents

  resources :snippets

    get 'auth/facebook/callback' => 'sessions#create'
    match 'auth/failure', to: redirect("/"), via: 'get'
    match 'signout', to: 'sessions#destroy', as: 'signout', via: 'get'
    match 'pims', to: 'public#index', as: 'pims', via: 'get'
    get "/p" => redirect("/piwik/index.php")
    get "/pims" => redirect("/pimsleur.html")

  
    namespace :admin do
    
        resources :pages, :navigations, :sites, :sections, :products, :product_categories, :product_images, :media, :costs, :leds, :led_configurations
        root to: "sites#index"
      
        get '/login' => 'sessions#new'
        post '/login' => 'sessions#create'
        get '/logout' => 'sessions#destroy'
        get '/signup' => 'users#new'
        post '/users' => 'users#create'  
        
      mount Ckeditor::Engine => '/ckeditor'
    end
      
    
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    
    resource :page
    resource :message
    get 'contact' => 'pages#contact'
    get 'store' => 'pages#store'
    get 'contact' => 'pages#contact'
    get 'diy' => 'pages#diy'
    get 'gallery' => 'pages#gallery'
    get 'blog' => 'pages#blog'
    get 'about' => 'pages#about'
    match '/contact',     to: 'contacts#new',        via: 'get'
    match '/send_mail', to: 'contact#send_mail', via: 'post'
    match '*path', to: redirect { |params, request| "/#{params[:locale]}" }, via: 'get'
    root to: 'pages#landing', as: "locale_root"
  end
  
  root to: redirect("/#{I18n.default_locale}")

  resources "contact", only: [:new, :create]

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Messagr from LEDYair website",
      :to => "support@ledyair.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/content.rb
class Content < ActiveRecord::Base
end

app/models/cost.rb
class Cost < ActiveRecord::Base
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base

belongs_to :site
has_many :images
end

app/models/hover.rb
class Hover < ActiveRecord::Base

belongs_to :page
end

app/models/image.rb
class Image < ActiveRecord::Base

belongs_to :gallery
 scope :sorted, lambda { order("images.position ASC") }
 
end

app/models/joiner.rb
class Joiner < ActiveRecord::Base

belongs_to :constituent
belongs_to :lamp
belongs_to :constituent_type

scope :leds, -> {where(constituent_type_id: 2)}


end

app/models/lamp.rb
class Lamp < ActiveRecord::Base

has_many :joiners
has_many :constituents, through: :joiners
has_many :constituents_types, through: :constituents
has_many :product_images

accepts_nested_attributes_for :constituents, :joiners, :product_images

scope :sortedp, lambda { order("lamps.sell ASC") }



include FriendlyId
friendly_id :model, :use => [:slugged]

end

app/models/led.rb
class Led < ActiveRecord::Base

has_and_belongs_to_many :led_configurations
translates :name, :description

end

app/models/map.rb
class Map < ActiveRecord::Base
end

app/models/media.rb
class Media < ActiveRecord::Base

has_and_belongs_to_many :pages

end

app/models/message.rb
class Message < ActiveRecord::Base

belongs_to :user


end

app/models/navigation.rb
class Navigation < ActiveRecord::Base

belongs_to :site
scope :sorted, lambda { order("navigations.order ASC") }
scope :visible, lambda {where(:display => true)}
translates :name

end

app/models/page.rb
class Page < ActiveRecord::Base

belongs_to :site
has_many :sections
has_many :images
has_many :hovers

 include FriendlyId
  friendly_id :name, :use => [:slugged]
end

app/models/product.rb
class Product < ActiveRecord::Base

translates :description
belongs_to :product_category
belongs_to :user
has_many :product_images

has_many  :leds,  through: :led_configurations
has_and_belongs_to_many :led_configurations


#has_and_belongs_to_many :led_configurations_products
#has_many  :led_configurations,  through: :led_configurations_products

# scope :visible, lambda { where(:visible => true) }
# scope :invisible, lambda { where(:visible => false) }
 scope :sortedp, lambda { order("products.price ASC") }
# scope :newest_first, lambda { order("pages.created_at DESC")}

include FriendlyId
friendly_id :name, :use => [:slugged]

 end

app/models/section.rb
class Section < ActiveRecord::Base

belongs_to :page
translates :header, :content

end

app/models/site.rb
class Site < ActiveRecord::Base

has_many :navigations
has_many :pages
has_one :store
has_many :product_categories, :through => :store
has_many :sections, :through => :pages
has_many :products, :through => :product_categories
has_many :galleries

 include FriendlyId
  friendly_id :name, :use => [:slugged]
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
end

app/models/store.rb
class Store < ActiveRecord::Base

belongs_to :site
has_many :product_categories

 include FriendlyId
  friendly_id :name, :use => [:slugged]
end

app/models/user.rb
class User < ActiveRecord::Base

has_secure_password
has_many :products
has_many :messages

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.image = auth.info.image
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

end

app/controllers/admin/store_controller.rb
class Admin::StoreController < Admin::BaseAdminController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end
end

app/controllers/admin/stores_controller.rb
class Admin::StoresController < Admin::BaseAdminController
  def index
  @page = Page.find(4)
  @title = @page.title
  @stores = Store.all
  
  end
  
  def show
    @store = Store.find(params[:id])
  end
  
  def new
    @store = Store.new
  end
  
  def create
    @store = Store.new(store_params)
    if @store.save
      flash[:success] = "Store created successfully"
      redirect_to polymorphic_path([:admin, @store])
    else
      @errors = @store.errors.full_messages
      render 'new'
    end
  end
  
  private
  
      def store_params
        params.require(:store).permit(:name, :site_id)
      end
end

app/controllers/store_controller.rb
class Admin::StoreController < Admin::BaseAdminController
  def index
  @page = Page.find(4)
  @title = @page.title
  end
  
  def show
    @store = Store.find(params[:id])
  end
  
  def new
    @store = Store.new(store_params)
  end
  
  def create
    @store = Store.new(store_params)
    if @store.save
      flash[:success] = "Store created successfully"
      redirect_to @store
    else
      @errors = @store.errors.full_messages
      render 'new'
    end
  end
  
  private
  
      def store_params
        require(:store).permit(:name, :site_id)
      end
end

app/helpers/admin/store_helper.rb
module Admin::StoreHelper
end

app/helpers/diy_helper.rb
module DiyHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/admin/store/create.html.erb
<h1>Admin::Store#create</h1>
<p>Find me in app/views/admin/store/create.html.erb</p>

app/views/admin/store/delete.html.erb
<h1>Admin::Store#delete</h1>
<p>Find me in app/views/admin/store/delete.html.erb</p>

app/views/admin/store/destroy.html.erb
<h1>Admin::Store#destroy</h1>
<p>Find me in app/views/admin/store/destroy.html.erb</p>

app/views/admin/store/edit.html.erb
<h1>Admin::Store#edit</h1>
<p>Find me in app/views/admin/store/edit.html.erb</p>

app/views/admin/store/index.html.erb
<h1>Admin::Store#index</h1>
<p>Find me in app/views/admin/store/index.html.erb</p>

app/views/admin/store/new.html.erb
<h1>Admin::Store#new</h1>
<p>Find me in app/views/admin/store/new.html.erb</p>

app/views/admin/store/show.html.erb
<h1>Admin::Store#show</h1>
<p>Find me in app/views/admin/store/show.html.erb</p>

app/views/admin/store/update.html.erb
<h1>Admin::Store#update</h1>
<p>Find me in app/views/admin/store/update.html.erb</p>

app/views/admin/stores/create.html.erb
<h1>Admin::Stores#create</h1>
<p>Find me in app/views/admin/stores/create.html.erb</p>

app/views/admin/stores/delete.html.erb
<h1>Admin::Stores#delete</h1>
<p>Find me in app/views/admin/stores/delete.html.erb</p>

app/views/admin/stores/destroy.html.erb
<h1>Admin::Stores#destroy</h1>
<p>Find me in app/views/admin/stores/destroy.html.erb</p>

app/views/admin/stores/eedit.html.erb
<h1>Admin::Stores#eedit</h1>
<p>Find me in app/views/admin/stores/eedit.html.erb</p>

app/views/admin/stores/index.html.erb
<h1>Admin::Stores#index</h1>
<p>Find me in app/views/admin/stores/index.html.erb</p>

<table border="1">
  <tr>
    <th>Store name</th><th>Site ID</th>
  </tr>
  <% @stores.each do |store| %>
  <tr><td><%= link_to(store.name, admin_store_path(store)) %></td><td><%= store.site_id%></td></tr>
  <% end %>



</table>

app/views/admin/stores/new.html.erb
<h1>Create store</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:store, :url => {:action => 'create'}) do |f| %>
    
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :site_id %>
      <%= f.select :site_id, 1..10, class: 'form-control' %>


      <%= f.submit "Create Store", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/stores/show.html.erb
<%= @store.name %>
<%= @store.site_id %>

app/views/admin/stores/update.html.erb
<h1>Admin::Stores#update</h1>
<p>Find me in app/views/admin/stores/update.html.erb</p>

app/views/store/js/_customLamp.html.erb
<script>
  var dynWidth = $("#width").val() * 1;
  var dynHeight = $("#height").val() * 1;
  var psuMargin = 1.2;
  var fans = $("#fanInput").val() * 1;
  var redw = $("#redw").val() * 1;
  var bluew = $("#bluew").val() * 1;
  var uvw = $("#uvw").val() * 1;
  var redCost = Math.ceil(1.9 * 16);
  var blueCost = Math.ceil(1.2 * 11);
  var uvCost = Math.ceil(7.6 * 10);
  var fanCost = 50;
  var margin = 2;
  var fansTotal = fanCost * fans;
  var redSell = (redw/25) * redCost;
  var blueSell = (bluew/25) * blueCost;
  var uvSell = (uvw/25) * uvCost;
  var misc = 50;
  
  //var watt = $(".lampWatt").val();
  var watt = 0;
  $(".controls").each(function(){
      
      $(this).find(".lampWatt").each(function(i,n){
        watt += parseInt($(n).val(),10); 
      });
      $(".wattValue").html("~" + watt + "W");
      //alert(watt);
    });
  
  var psu = Math.ceil(watt * psuMargin);
  
  
  $("#lampSizeValue").html("H: " + dynHeight + " W: " + dynWidth);
  $("#paypalInputSize").val(dynHeight + "," + dynWidth);
  $("#paypalInputWatt").val("red: " + redw + "," + "blue: " + bluew + "," + "uv: " + uvw );
  $("#paypalInputPsu").val(psu);
  $("#paypalInputFans").val(fans);
  $(".sizeValue").html(dynHeight + "X" + dynWidth);
  $(".psuValue").html(psu);
  $(".fansValue").html(fans);
  $("#lamp").width(dynWidth * 4);
  $("#lamp").height(dynHeight * 4);
  
  $("#psuInput").val(psu);
  //$("#fanInput").val(fans);
  
  var totalSell = Math.ceil((redSell + blueSell + uvSell + misc + psu + fansTotal) * margin);
  $("#diyPrice").html(totalSell);
  $("#paypalTotal").val(totalSell);
  
  /////////////////////////////////// CHANGE //////////////////////////////////
  $(".controls input").change(function () {
      
      var dynWidth = $("#width").val() * 1;
      var dynHeight = $("#height").val() * 1;
      
      var redw = $("#redw").val() * 1;
      var bluew = $("#bluew").val() * 1;
      var uvw = $("#uvw").val() * 1;
      var redCost = Math.ceil(1.9 * 16);
      var blueCost = Math.ceil(1.2 * 11);
      var uvCost = Math.ceil(7.6 * 10);
      var redSell = (redw/25) * redCost;
      var blueSell = (bluew/25) * blueCost;
      var uvSell = (uvw/25) * uvCost;
      
      var fans = $("#fanInput").val() * 1;
      var fansTotal = fanCost * fans;
      //$("#test").html("red:" + redSell + ", blue: " + blueSell + ", uv: " + uvSell + ", misc: " + misc + ", psu: " + psu + ", fans: " + fansTotal );
      $("#width").val(dynWidth);
      $("#height").val(dynHeight);
  
      $("#paypalInputSize").val(dynHeight + "," + dynWidth);
      $("#paypalInputFans").val(fans);
      
      //$("#fanInput").val(fans);
      
      $(".sizeValue").html(dynHeight + "X" + dynWidth);
      $(".fansValue").html(fans);
      
      $("#paypalInputWatt").val("red: " + redw + "," + "blue: " + bluew + "," + "uv: " + uvw );
      //alert(dynWidth);
      $("#lamp").width(dynWidth * 4);
      $("#lamp").height(dynHeight * 4);
      
      var watt = 0;
      $(".controls").each(function(){
        $(this).find(".lampWatt").each(function(i,n){
            watt += parseInt($(n).val(),10); 
        });
      $(".wattValue").html("~" + watt + "W");
        //alert(watt);
      });
      
      var psu = Math.round(watt * psuMargin);
      var leds = Math.ceil(redSell + blueSell + uvSell) * 1;
      var totalSell = Math.ceil((leds + misc + psu + fansTotal) * margin);
      $("#psuInput").val(psu);
      $(".psuValue").html(psu);
      $("#paypalInputPsu").val(psu);
      $("#paypalTotal").val(totalSell);
      $("#diyPrice").html(totalSell);
  });
</script>